version: "3.8"

services:
  doggys-app:
    #depends_on:
      #- doggys-db
      #- celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    image: doggys_service
    container_name: doggys_service_container
    environment:
      - WEB_APP_TITLE=guane Intern Fastapi - gateway
      - WEB_APP_DESCRIPTION=This is a app about adopt dogs - Technical test
      - WEB_APP_VERSION=1.0
      - SECRET_KEY=cfd11da5af04ab43747b19afdddfb5a82914a793f21c5209b4c9e2ae3fcad009
      - ALGORITHM=HS256
      - DATABASE_URL=postgres://postgres:postgres@doggys_db:5432/doggys
      - DATABASE_SERVICE_URL=http://doggys_db_service_container:8004 #Llega solo hasta el puerto
      - DATABASE_TEST_URL=sqlite://:memory
      - IMAGE_API=https://dog.ceo/api/breeds/image/random
      - INITIAL_EMAIL="init@mail.com"
      - INITIAL_PASSWORD="SecurePassword"
      - C_FORCE_ROOT=false
      - DEBUGGER=False
    ports:
      - 8000:8000
      - 10019:10019
    # env_file:
    #   - .env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/
    networks:
      doggys-network:
        aliases:
          - doggys_ervice


  # doggys-db:
  #   build:
  #     context: ./data
  #     dockerfile: Dockerfile
  #   image: doggys_db
  #   container_name: doggys_db_container
  #   restart: always
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "postgres"
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata_doggys:/var/lib/postgresql/data
  #   networks:
  #     doggys-network:
  #       aliases:
  #         - doggys_db


  # celery-worker:
  #   depends_on:
  #     - rabbitmq
  #     - redis
  #   build:
  #     context: ./celery_app
  #     dockerfile: Dockerfile
  #   image: celery_worker
  #   container_name: celery_worker_container
  #   env_file:
  #     - .env
  #   command: celery -A task worker -Q hipri -l INFO
  #   volumes:
  #     - ./:/usr/src/app/
  #   networks:
  #     doggys-network:
  #       aliases:
  #         - celery_worker


  # redis:
  #   image: bitnami/redis:5.0.4
  #   environment:
  #     - REDIS_PASSWORD=password123
  #   ports:
  #     - 6379:6379
  #   expose:
  #     - 6379
  #   networks:
  #     doggys-network:
  #       aliases:
  #         - doggys_redis


  # rabbitmq:
  #   image: bitnami/rabbitmq:latest
  #   environment:
  #     - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1000000000
  #   ports:
  #     - 15672:15672
  #   networks:
  #     doggys-network:
  #       aliases:
  #         - doggys_rabbit
  #   volumes:
  #     - rabbitmqstats_data:/var/lib/postgresql/data


volumes:
  pgdata_doggys:
    external: true
  rabbitmqstats_data:
    external: true


networks:
  doggys-network:
    external: true
