version: "3.8"

services: 
  doggys-db:
    build: 
      context: ./data
      dockerfile: Dockerfile
    image: doggys_db
    container_name: doggys_db_container
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
    volumes: 
      - pgdata_doggys:/var/lib/postgresql/data
    networks: 
      doggys-network:
        aliases: 
          - doggys_db

  doggys-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: doggys_service
    container_name: doggys_service_container
    ports:
      - 8000:8000
    env_file:
      - .env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/
    networks: 
      doggys-network:
        aliases: 
          - doggys_ervice 
          

volumes: 
  pgdata_doggys:
    external: true     

networks:
  doggys-network:
    external: true
