name: push

on:
  push:
    branches: ["**"]

jobs:
  pre-commit-and-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Pre-Commit
        uses: pre-commit/action@v2.0.3
